apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: farseer-agent
  labels:
    app: farseer-agent
    k8s.kuboard.cn/layer: cloud
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: farseer-agent
  template:
    metadata:
      name: farseer-agent
      labels:
        app: farseer-agent
    spec:
      # 是否允许部署到Master节点上
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: farseer-agent
          image: farseernet/farseer-agent:7.x
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          envFrom: #以密文的方式，把配置项写到env
            - secretRef:
                name: farseer-agent
          env:
            - name: "NODE_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: sock
              mountPath: /var/run/docker.sock
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: sock
          hostPath:
            path: /var/run/docker.sock
        - name: localtime
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
data:
  ElasticSearch__log_es: "" #elasticsearch
kind: Secret
metadata:
  name: farseer-agent
  namespace: default
type: Opaque